apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: producer
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/justin2997/knative-rabbitmq-producer
            args:
              - '--routingKey=logger1.default'