apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: logger3
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/gswk/logger:latest